mqtt: 
    server: 127.0.0.1
    port: 1883
    keepalive: 30
    username: test
    password: test
    subtopics:
        - Basic
        - vibration
        - Abrpower
        - XAbracceleration
        - YAbracceleration
        - ZAbracceleration
        - XAbrvelocity
        - YAbrvelocity
        - ZAbrvelocity
        - Machineheat
        - Transferdata
oracle:
    server: 127.0.0.1
    port: 1521
    servicename: test
    user: test
    password: test
kafka:
    server: 127.0.0.1:9092,127.0.0.2:9092,127.0.0.3:9092
    topic: cncmqtt
    consumergroup: mqttinfo
    consumerid: mqttinfo01